# The .DAT files which are output by the Campbell Scientific CR21 datalogger we
# used with our IRGA were in a format unreadable by excel. The following
# script cleans up these data using a manual "alternating line" process that
# works on these scripts only because the data lines are consistently broken 
# across 3 lines btwn the 8th and 9th columns.
#
# This means that in cases where a unique leading line of data was written by 
# the CR21 (i.e. some sort of file header), those cells were removed prior
# to the running of this script to preserve the correct alternation.
# 
# The every output file was manually examined in its entirety and manipulated to 
# add relevant information, ensuring confidence in the process.
#
# Load packages for this script:
library(lubridate)
library(tidyverse)
library(tundra)
library(here)
#
# This function loads a CR21 .DAT file into R an creates a clean tibble.
Prep_CR21_File <- function(file){
  # Loading the data without any sort of delimination (columns get deliminated
  # later, so a comma is used because they are not present).
  IRGA <- read_delim(paste(here("data/IRGA_flux/data_logger_files/"), file, sep = ""), 
                     delim = ",",
                     col_names = FALSE) %>%
    mutate(row_number = row_number())
  
  # Subsetting the even lines of data
  IRGA_even <- IRGA %>%
    filter(FALSE == FSA::is.odd(IRGA$row_number)) %>%
    mutate(row_number = as.numeric(row_number) - 1)
  
  # Putting the even and odd lines of data together on the same line.
  IRGA <- full_join(IRGA, IRGA_even, by = "row_number") %>%
    filter(TRUE == FSA::is.odd(IRGA$row_number)) %>%
    select(X1.x, X1.y)
  
  # I use regular expressions to seperate the columns based on the 
  # "<column number>+<numeric data> format that the CR21 outputs.
  # This first section is what was on the odd lines of data. Column names are 
  # inflexibly generated by location of column (since this order never changed
  # for me).
  IRGA[c("blank",
         "X1",
         "year",
         "DOY",
         "hhmm",
         "ss.s",
         "battery_V",
         "CO2_v",
         "CO2_ppm")] <- str_split(IRGA$X1.x,
                                  "[0-9]{2}(?=[\\+,\\-])",
                                  9,
                                  simplify = TRUE)
  
  # This second section is for the even lines of data, with the same process
  # for selecting and naming columns based on order.
  IRGA[c("blank",
         "H2O_v",
         "H2O_ppt",
         "T_panel",
         "T_soil",
         "T_air",
         "X14",
         "X15")] <- str_split(IRGA$X1.y,
                              "[0-9]{2}(?=[\\+,\\-])",
                              8,
                              simplify = TRUE)
  
  # Creating the IRGA tibble in the global environment and assigning four empty 
  # columns to manual fill the appropriate information from lab notebooks.
  IRGA <<- IRGA %>%
    add_column("site" = NA,
               "plot" = NA,
               "treatment" = NA,
               "light" = NA) %>%
    select(c(site:light,
             X1:X15))
}

for(i in list.files(path = here("data/IRGA_flux/data_logger_files"), 
                    pattern = "\\.DAT")){
  Prep_CR21_File(i)
  
  # Writing the files to a new directory.
  write_csv(IRGA, paste(here("data/IRGA_flux/converted_files/"), 
                        tools::file_path_sans_ext(i), 
                        ".csv", sep = ""))
}
